### ISSUE TITLE
111

### ISSUE THREAD

**Issue by chaishuhang** [HVision-NKU/SRFormer#1]
运行您提供的SRFormerLight_SRx4_DIV2K.pth模型，在set5数据集上结果如下：
![2](https://user-images.githubusercontent.com/129351481/229807321-dcb2e34b-3c54-40c5-b03e-151ede5a75b4.JPG)

**Comment by chaishuhang** [comment]
好的，谢谢。请问您大概用几个GUP跑了多久呢？

**Comment by Z-YuPeng** [comment]
您好，SRFormerLight_SRx4_DIV2K.pth这个模型大约需要两个NVIDIA GeForce RTX 3090跑两天，如果您熟悉SwinIR，也可以大致参考SwinIR的训练时间。

**Comment by CR7forMadrid** [comment]
> 您好，论文表格中的数据没有问题，推荐您按照这里的步骤得到论文中的五个数据集，进行评测：https://github.com/yulunzhang/RCAN#the-whole-test-pipeline

Hello, so calculating PSNR/SSIM generally does not apply to the results of basicSR output? Does it have to be recalculated by matlab script?
