### ISSUE TITLE
Thank you :) Wanted to show you my SRFormer_light model :)

### ISSUE THREAD

**Issue by Phhofm** [HVision-NKU/SRFormer#10]
Thank you for this network :)
I just wanted to show real quick that I have trained a (4x) SRFormer_light model for anime super-resolution with real degradation (compression, noise, blur), and created visual outputs which can be compared to a SwinIR_light (=small) model I have trained on the same dataset with the same config (so same losses, gt_size, batch size, both from scratch meaning no pretrain). Just one visual comparison (more outputs in the link below) of Input, SwinIR_light and SRFormer_light:

![grafik](https://github.com/HVision-NKU/SRFormer/assets/14755670/75dd37c0-a5bf-4a22-8e4d-1392c9001bf0)

More visual outputs can be found [here](https://github.com/Phhofm/models/tree/main/4xHFA2kLUDVAE_results) and the trained SRFormer_light model file can be found [here](https://github.com/Phhofm/models/tree/main/4xHFA2kLUDVAESRFormer_light)

**Comment by Z-YuPeng** [comment]
Greatful! The model you trained demonstrates the performance of SRFormer in anime SR. I want to express my sincere gratitude for your work.

**Comment by Phhofm** [comment]
PS I think SRFormer is impressive and its results are growing on me. I trained/finetunes another model (not lightweight but base SRFormer) and I think the results are very good even when compared with HAT-L (which is a bigger and slower arch/model, trained with the same config). It is trained with otf jpg compression and blur. Here are results compared with Real-ESRGAN (RRDBNet) and HAT-S and HAT-L

https://imgsli.com/MTg5MDY3/0/3
https://imgsli.com/MTg5MDYy/0/3
https://imgsli.com/MTg5MDY1/0/3

The model files (pth and onnx conversions in the onnx folder) with training info can be found [here](https://github.com/Phhofm/models/tree/main/4xNomos8kSCSRFormer)

![seeufer](https://github.com/Phhofm/models/raw/main/4xNomos8kSC_results/seeufer.png)
![bibli](https://github.com/Phhofm/models/raw/main/4xNomos8kSC_results/bibli.png)
![dearalice](https://github.com/Phhofm/models/raw/main/4xNomos8kSC_results/dearalice.png)

**Comment by Z-YuPeng** [comment]
SRFormer is accept by ICCV 2023,  We will enrich our repo recently and provide more demos, and we will add a link in our repo about the third-party model you trained so that people can learn more about SRFormer！

**Comment by Feynman1999** [comment]
> PS I think SRFormer is impressive and its results are growing on me. I trained/finetuned another model (not lightweight but an SRFormer base model) and I think the results are very good even when compared with HAT-L (which is a bigger and slower arch/model, trained with the same config). It is trained with otf jpg compression and blur. Here are results compared with Real-ESRGAN (RRDBNet) and HAT-S and HAT-L
> 
> https://imgsli.com/MTg5MDY3/0/3 https://imgsli.com/MTg5MDYy/0/3 https://imgsli.com/MTg5MDY1/0/3
> 
> The model files (pth and onnx conversions in the onnx folder) with training info can be found [here](https://github.com/Phhofm/models/tree/main/4xNomos8kSCSRFormer)
> 
> ![seeufer](https://github.com/Phhofm/models/raw/main/4xNomos8kSC_results/seeufer.png) ![bibli](https://github.com/Phhofm/models/raw/main/4xNomos8kSC_results/bibli.png) ![dearalice](https://github.com/Phhofm/models/raw/main/4xNomos8kSC_results/dearalice.png)

excelent work! can you share some info about your training dataset?  that's helpful to me !

**Comment by terrainer** [comment]
> > PS I think SRFormer is impressive and its results are growing on me. I trained/finetuned another model (not lightweight but an SRFormer base model) and I think the results are very good even when compared with HAT-L (which is a bigger and slower arch/model, trained with the same config). It is trained with otf jpg compression and blur. Here are results compared with Real-ESRGAN (RRDBNet) and HAT-S and HAT-L
> > https://imgsli.com/MTg5MDY3/0/3 https://imgsli.com/MTg5MDYy/0/3 https://imgsli.com/MTg5MDY1/0/3
> > The model files (pth and onnx conversions in the onnx folder) with training info can be found [here](https://github.com/Phhofm/models/tree/main/4xNomos8kSCSRFormer)
> > ![seeufer](https://github.com/Phhofm/models/raw/main/4xNomos8kSC_results/seeufer.png) ![bibli](https://github.com/Phhofm/models/raw/main/4xNomos8kSC_results/bibli.png) ![dearalice](https://github.com/Phhofm/models/raw/main/4xNomos8kSC_results/dearalice.png)
> 
> excelent work! can you share some info about your training dataset? that's helpful to me !

The dataset used is [HFA2K_LUDVAE](https://discord.com/channels/547949405949657098/905446120333930566/1098686154364158103), available in the #dataset-releases channel of the [Enhance Everything! Discord server](https://discord.gg/cpAUpDK).
