### ISSUE TITLE
Question about training machine.

### ISSUE THREAD

**Issue by mls1999725** [HVision-NKU/SRFormer#16]
Thanks for your excellent work! I would like to ask how many GPUs are used for training SRFormer and SwinIR? What type of GPUs are they? Looking forward to your reply.

**Comment by Z-YuPeng** [comment]
Hi!
For the official setting, you may require two 3090 GPUs to train SRFormer or SwinIR. You can decrease the batch size, window size, patch size, and other hyper-parameters to train it on less GPU. I encourage you to try to configure these hyper-parameters！

**Comment by Z-YuPeng** [comment]
We will close the issue since it has been inactive for a long time. Feel free to reopen it when you need.
