### ISSUE TITLE
How to draw the power spectrum of the intermediate feature map？

### ISSUE THREAD

**Issue by szw811** [HVision-NKU/SRFormer#23]
Hello, .I would like to ask how to draw the power spectrum of the intermediate feature mapping as shown in Figure 4 in the paper.

**Comment by Z-YuPeng** [comment]
Hi, maybe you can find useful things here https://github.com/HVision-NKU/SRFormer/issues/4

**Comment by szw811** [comment]
> Hi, maybe you can find useful things here #4

Thank you very much for your reply!

**Comment by Z-YuPeng** [comment]
I closed the issue since it is finished, feel free to reopen it if you would like any help!
