### ISSUE TITLE
what is the batch size in DF2K experiments?

### ISSUE THREAD

**Issue by erzhu222** [HVision-NKU/SRFormer#30]
Thanks for your perfect work, and I have  two questions: 
1. what is the batch size and input resolusion in the DF2K experiments train in your paper? 
2. what is the iteration number in DF2K train process?
thanks a lot!

**Comment by Z-YuPeng** [comment]
Sorry for the late, I trained SRFormer on Real-ESRGAN earlier, but have not yet had the opportunity to verify its correctness due to being preoccupied with another project.  Today, I briefly checked this model. If there are no issues, I plan to update the repo within a week.

**Comment by Z-YuPeng** [comment]
Sorry for the late, this setting can be found in our paper, The batch size is set to 32, the input resolution is 48x48, and the number of iterations is 500k.
