### ISSUE TITLE
KeyError: "No object named 'SwinIR_bw8mlp5' found in 'arch' registry!"

### ISSUE THREAD

**Issue by await-you** [HVision-NKU/SRFormer#32]
有遇到这个问题的吗？

**Comment by Z-YuPeng** [comment]
你好，请问是运行哪一个代码出现了这个问题？

**Comment by await-you** [comment]
感谢回复！


按照readme 配置环境后，执行命令  ./scripts/dist_train.sh 4 options/train/SRFormer/train_SRFormer_SRx4_scratch.yml后报错的。

![image](https://github.com/HVision-NKU/SRFormer/assets/50796392/bafd30e6-6195-4e74-ab11-195628c016f1)
配置文件中，有这个名称

**Comment by Z-YuPeng** [comment]
这个model_type SwinIR-bw8mlp5 是在哪里找的呀？ 仓库里面应该没有这个名称？

**Comment by Z-YuPeng** [comment]
抱歉，刚看了一下, x3 的 config 名称写错了，再pull 一下试试吧

**Comment by await-you** [comment]
我找到问题了，之前我下载过您的代码，那个版本中的配置文件中
SRFormer/options/train/SRFormer/train_SRFormer_SRx4_scratch.yml&nbsp;&nbsp;



实在抱歉哈，我重新下载现在的代码，麻烦您啦，万分感谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yupeng ***@***.***&gt;; 
发送时间: 2024年4月28日(星期天) 晚上11:00
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [HVision-NKU/SRFormer] KeyError: &quot;No object named &#39;SwinIR_bw8mlp5&#39; found in &#39;arch&#39; registry!&quot; (Issue #32)














 
这个model_type SwinIR-bw8mlp5 是在哪里找的呀？ 仓库里面应该没有这个名称？
