### ISSUE TITLE
Where to download SRFormerV2 model?

### ISSUE THREAD

**Issue by AIisCool** [HVision-NKU/SRFormer#37]
@houqb @Z-YuPeng The google drive only has the previous SFormer models. Will V2 be available to download?

Thank you for all your work!

**Comment by Z-YuPeng** [comment]
Hi, thanks for your interest, we are reorganizing our code now and will update it soon.

**Comment by AIisCool** [comment]
Looking forward to it. Thank you for the quick reply!
