### ISSUE TITLE
Figure 4

### ISSUE THREAD

**Issue by Hao-Xin-Shen** [HVision-NKU/SRFormer#4]
Hi author, I am very interested in your visualization of Figure 4, how did you draw this figure? Thank you so much for teaching me this.

**Comment by Z-YuPeng** [comment]
Sorry for the late reply, I've been too busy recently to read issues. I draw picture using the code below.

cNorm = colors.Normalize(vmin=0, vmax=1)
cm = plt.get_cmap('hot_r')
scalarMap = mplcm.ScalarMappable(norm=cNorm, cmap=cm)
plt.plot(x, y, linewidth =4.0,color=scalarMap.to_rgba(({ add your percentage}) )

**Comment by Z-YuPeng** [comment]
> Thank you very much for your reply. I'm sorry I didn't describe my problem clearly. I want to know what to do with an intermediate feature to get its Frequency and Log Amplitude Power. I would appreciate it if you could teach me.
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "HVision-NKU/SRFormer" ***@***.***&gt;; 发送时间:&nbsp;2023年5月19日(星期五) 下午3:56 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [HVision-NKU/SRFormer] Figure 4 (Issue #4) Sorry for the late reply, I've been too busy recently to read issues. I draw picture using the code below. cNorm = colors.Normalize(vmin=0, vmax=1) cm = plt.get_cmap('hot_r') scalarMap = mplcm.ScalarMappable(norm=cNorm, cmap=cm) plt.plot(x, y, linewidth =4.0,color=scalarMap.to_rgba(({ add your percentage}) ) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

Got it, maybe this link will help you:
https://bertvandenbroucke.netlify.app/2019/05/24/computing-a-power-spectrum-in-python/
