### ISSUE TITLE
how to inference my own image?

### ISSUE THREAD

**Issue by junhyoung-ew** [HVision-NKU/SRFormer#9]
I think that test code is evaluation for training.

I use pretrained model for inference.

Can you guide me? 

Thank you.

**Comment by Z-YuPeng** [comment]
Thanks for your attention. We do not provide code for doing that directly. You can modify the basicsr/test.py.
I would like to give you a example:
    # create model
    model = build_model(opt)
    ### inference
    with torch.no_grad():
        network = model.net_g.module
        input = set5.__getitem__(0)["lq"].to("cuda").unsqueeze(0)
        output = network(input)

**Comment by Z-YuPeng** [comment]
if the gpu_num = 1 
`network = model.net_g` instead of `network = model.net_g.module`
